//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suteki.TardisBank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suteki.TardisBank.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not withdraw {0} because you only have {1} in your account.
        /// </summary>
        public static string FormatCanNotWithdraw {
            get {
                return ResourceManager.GetString("FormatCanNotWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a child of {1}.
        /// </summary>
        public static string FormatIsNotAChildOf {
            get {
                return ResourceManager.GetString("FormatIsNotAChildOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message with Id {0} found for user &apos;{1}&apos;.
        /// </summary>
        public static string FormatNoMessageWithIdForUser {
            get {
                return ResourceManager.GetString("FormatNoMessageWithIdForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment from {0}.
        /// </summary>
        public static string FormatPaymentFrom {
            get {
                return ResourceManager.GetString("FormatPaymentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/{0}.
        /// </summary>
        public static string FormatUserId {
            get {
                return ResourceManager.GetString("FormatUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} would like to withdraw {1}.
        /// </summary>
        public static string FormatWouldLikeToWithdraw {
            get {
                return ResourceManager.GetString("FormatWouldLikeToWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing description parameter.
        /// </summary>
        public static string MissingDescriptionParameter {
            get {
                return ResourceManager.GetString("MissingDescriptionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parent parameter.
        /// </summary>
        public static string MissingParentParameter {
            get {
                return ResourceManager.GetString("MissingParentParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Your Parent.
        /// </summary>
        public static string NotYourParent {
            get {
                return ResourceManager.GetString("NotYourParent", resourceCulture);
            }
        }
    }
}
